name: Nightly Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-release:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and release
      run: |
        npm ci
        npm run build
        npm run release
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
